"use client";
import { ChakraProvider, Divider } from "@chakra-ui/react";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./Componant/NavBar";
import Footer from "./Componant/Footer";
import Wrapper from "./Context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Wrapper>
            <NavBar />
            {children}
            <Footer />
          </Wrapper>
        </ChakraProvider>
      </body>
    </html>
  );
}
